name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator, OS=15.0, name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: |
          xcodebuild clean test -project TestingCi.xcodeproj -scheme TestingCi -destination "${destination}" CODE_SIGN_IDENTITY="QL_Dist_Provisioning_Profile_28Jan_2022" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
