name: CI-CD (Demo)

on: push

jobs:
  deploy:
    name: Complete CI-CD Job
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Choosing Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
        
      - name: Xcode version 
        run: /usr/bin/xcodebuild -version
        
      - name: Build Clean
        run: |
          echo "Your Build Folder is Cleaning"
          xcodebuild clean -project TestingCi.xcodeproj -scheme TestingCi | xcpretty
          
      - name: Build Test
        run: |
          echo "Your Build is Testing"
#          xcodebuild test -project TestingCi.xcodeproj -scheme TestingCi -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty -s
      
      - name: Install gpg
        run: brew install gnupg
        
      - name: Setup Provisioning Profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
        
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_app.sh
      
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
        
#      - name: Archiving Project
#        env:
#          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
#        run: |
#          xcodebuild  -workspace TestingCi.xcworkspace \
#          -scheme TestingCi \
#          -sdk iphoneos \
#          -configuration Release \
#          -archivePath $PWD/build/TestingCi.xcarchive \
#          clean archive | xcpretty

