name: CI-CD (Demo)

on: push

jobs:
  build_project:
    name: Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Choosing Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Xcode version 
        run: /usr/bin/xcodebuild -version
