name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator, OS=15.0, name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean -project TestingCi.xcodeproj -scheme TestingCi | xcpretty
#         env: 
#          destination: ${{ matrix.destination }}
