name: CI-CD

on: 
  push:
    tags:        
      - Mj.**

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator, OS=15.0, name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: |
          echo "Testing"
        env: 
         destination: ${{ matrix.destination }}
