name: CI-CD (Demo)

on: push

jobs:
  build_project:
    name: Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Choose Xcode
        run: |
	sudo Xcode-select -switch /Applications/Xcode_Version 13.0.app
